import { designSystem } from '@cutsync/brand';

export const businessTheme = {
  colors: {
    canvas: '#0B100D',
    canvasRaised: '#111813',
    surface: '#172019',
    surfaceRaised: '#1E2921',
    surfaceMuted: '#263229',
    border: '#344238',
    borderStrong: '#46564A',
    text: '#F4F6F4',
    textSoft: '#C4CDC6',
    textMuted: '#87938A',
    accent: '#D8BE7C',
    accentStrong: '#F1D993',
    accentSoft: '#332F20',
    success: '#7BC68B',
    successSoft: '#183521',
    warning: '#E0B65E',
    warningSoft: '#3A2E18',
    danger: '#ED8C82',
    dangerSoft: '#3B1D1B',
    info: '#91B7E4',
    infoSoft: '#182B3D',
    white: '#FFFFFF',
  },
  spacing: {
    xxs: designSystem.spacing.xxs,
    xs: designSystem.spacing.xs,
    sm: designSystem.spacing.sm,
    md: designSystem.spacing.md,
    lg: designSystem.spacing.lg,
    xl: designSystem.spacing.xl,
    xxl: designSystem.spacing.xxl,
  },
  radii: {
    sm: 10,
    md: 14,
    lg: 20,
    pill: 999,
  },
  typography: {
    display: {
      fontSize: 34,
      lineHeight: 38,
      fontWeight: '800' as const,
      letterSpacing: -1.1,
    },
    title: {
      fontSize: 24,
      lineHeight: 29,
      fontWeight: '800' as const,
      letterSpacing: -0.6,
    },
    heading: {
      fontSize: 17,
      lineHeight: 22,
      fontWeight: '800' as const,
      letterSpacing: -0.2,
    },
    body: {
      fontSize: 14,
      lineHeight: 21,
      fontWeight: '400' as const,
    },
    bodyStrong: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700' as const,
    },
    caption: {
      fontSize: designSystem.typography.minimumFunctionalSize,
      lineHeight: designSystem.typography.caption.lineHeight,
      fontWeight: '600' as const,
    },
    eyebrow: {
      fontSize: designSystem.typography.minimumFunctionalSize,
      lineHeight: designSystem.typography.caption.lineHeight,
      fontWeight: '900' as const,
      letterSpacing: 1.45,
      textTransform: 'uppercase' as const,
    },
  },
  sizing: {
    control: 50,
    touchTarget: designSystem.sizing.minimumTouchTarget,
    contentMaxWidth: 720,
  },
  opacity: {
    pressed: designSystem.opacity.pressed,
    disabled: designSystem.opacity.disabled,
  },
} as const;
