import React, { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LockKeyhole, ShieldCheck, UserMinus } from 'lucide-react-native';
import { useGovernanceAuth } from '../../contexts/governance-auth-context';
import { AppButton } from '../ui/AppButton';
import { AppCard } from '../ui/AppCard';
import { AppInput } from '../ui/AppInput';
import { InlineNotice } from '../ui/InlineNotice';
import { colors, layout, typography } from '../../theme/tokens';
import { grantGovernanceRole, listGovernanceInvitations, listGovernanceMemberships, listGovernanceUsers, revokeGovernanceInvitation, revokeGovernanceMembership, revokeGovernanceRole } from '../../services/governance-compliance';
import type { GovernanceInvitation, GovernanceMembership, GovernanceUser } from '../../types/governance-compliance';
import type { GovernanceRole } from '../../types/governance-knowledge';

export function GovernanceAccess() {
  const { profile } = useGovernanceAuth(); const owner = profile?.role === 'SaaS_Owner';
  const [users,setUsers]=useState<GovernanceUser[]>([]); const [memberships,setMemberships]=useState<GovernanceMembership[]>([]); const [invitations,setInvitations]=useState<GovernanceInvitation[]>([]); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState<{tone:'success'|'danger';message:string}|null>(null); const [reason,setReason]=useState(''); const [profileId,setProfileId]=useState(''); const [role,setRole]=useState<GovernanceRole>('SaaS_Viewer'); const [active,setActive]=useState<string|null>(null);
  const load=async()=>{setLoading(true);try{const [u,m,i]=await Promise.all([listGovernanceUsers(),listGovernanceMemberships(),listGovernanceInvitations('pending')]);setUsers(u);setMemberships(m);setInvitations(i);}catch(e){setNotice({tone:'danger',message:e instanceof Error?e.message:'Não foi possível carregar o acesso.'});}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
  const changeRole=async()=>{if(!profileId||reason.trim().length<10){setNotice({tone:'danger',message:'Informe um profile_id existente e uma justificativa de pelo menos 10 caracteres.'});return;}setActive(profileId);try{await grantGovernanceRole(profileId,role,reason);setNotice({tone:'success',message:'Papel de Governança atualizado.'});setProfileId('');setReason('');await load();}catch(e){setNotice({tone:'danger',message:e instanceof Error?e.message:'Falha ao alterar papel.'});}finally{setActive(null);}};
  const removeRole=async(id:string)=>{if(reason.trim().length<10){setNotice({tone:'danger',message:'A remoção exige justificativa.'});return;}setActive(id);try{await revokeGovernanceRole(id,reason);setNotice({tone:'success',message:'Papel removido.'});setReason('');await load();}catch(e){setNotice({tone:'danger',message:e instanceof Error?e.message:'Falha ao remover papel.'});}finally{setActive(null);}};
  const revokeMembership=async(item:GovernanceMembership)=>{if(reason.trim().length<10){setNotice({tone:'danger',message:'A revogação exige motivo.'});return;}setActive(item.id);try{await revokeGovernanceMembership(item.id,reason);setNotice({tone:'success',message:'Membership revogado.'});setReason('');await load();}catch(e){setNotice({tone:'danger',message:e instanceof Error?e.message:'Falha ao revogar membership.'});}finally{setActive(null);}};
  const revokeInvite=async(item:GovernanceInvitation)=>{if(reason.trim().length<10){setNotice({tone:'danger',message:'A revogação exige motivo.'});return;}setActive(item.id);try{await revokeGovernanceInvitation(item.id,reason);setNotice({tone:'success',message:'Convite revogado.'});setReason('');await load();}catch(e){setNotice({tone:'danger',message:e instanceof Error?e.message:'Falha ao revogar convite.'});}finally{setActive(null);}};
  return <ScrollView contentContainerStyle={styles.page} testID="governance-access-screen"><Text style={styles.eyebrow}>CONTROLE DE ACESSO</Text><Text style={styles.title}>Papéis e memberships</Text><Text style={styles.description}>Papéis globais só podem ser gerenciados pelo Owner. Memberships e convites são revogados por RPC, sem alterar diretamente o perfil.</Text>{!!notice&&<InlineNotice tone={notice.tone} message={notice.message}/>}<AppInput label="Justificativa da alteração" value={reason} onChangeText={setReason} placeholder="Motivo obrigatório para qualquer mudança" multiline/>{owner&&<AppCard style={styles.card}><View style={styles.row}><LockKeyhole color={colors.brand} size={20}/><Text style={styles.sectionTitle}>Conceder ou alterar papel</Text></View><AppInput label="profile_id já cadastrado" value={profileId} onChangeText={setProfileId} placeholder="UUID do perfil"/><View style={styles.tabs}>{(['SaaS_Viewer','SaaS_Editor','SaaS_Owner'] as GovernanceRole[]).map(value=><AppButton key={value} label={value} onPress={()=>setRole(value)} variant={role===value?'primary':'secondary'} size="sm"/>)}</View><AppButton label="Salvar papel" onPress={()=>void changeRole()} loading={active===profileId}/></AppCard>}{loading?<ActivityIndicator color={colors.brand} style={styles.loader}/>:<><Text style={styles.sectionTitle}>Usuários da Governança</Text><View style={styles.grid}>{users.map(user=><AppCard key={user.profile_id} style={styles.card}><View style={styles.row}><ShieldCheck color={colors.success} size={18}/><Text style={styles.cardTitle}>{user.name}</Text><Text style={styles.status}>{user.role}</Text></View>{user.email&&<Text style={styles.meta}>{user.email}</Text>}{owner&&<AppButton label="Remover papel" onPress={()=>void removeRole(user.profile_id)} loading={active===user.profile_id} variant="danger" icon={<UserMinus size={15} color={colors.danger}/>}/>}</AppCard>)}</View><Text style={styles.sectionTitle}>Memberships ativos e revogados</Text><View style={styles.grid}>{memberships.map(item=><AppCard key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.profile_name}</Text><Text style={styles.meta}>{item.establishment_name} · {item.role} · {item.status}</Text>{item.status==='active'&&<AppButton label="Revogar membership" onPress={()=>void revokeMembership(item)} loading={active===item.id} variant="danger"/>}</AppCard>)}</View><Text style={styles.sectionTitle}>Convites pendentes</Text><View style={styles.grid}>{invitations.map(item=><AppCard key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.establishment_name}</Text><Text style={styles.meta}>{item.invited_email} · {item.role}</Text><AppButton label="Revogar convite" onPress={()=>void revokeInvite(item)} loading={active===item.id} variant="danger"/></AppCard>)}</View></>}</ScrollView>;
}
const styles=StyleSheet.create({page:{width:'100%',maxWidth:layout.contentMax,alignSelf:'center',padding:24,gap:16,paddingBottom:80},eyebrow:{color:colors.brand,fontFamily:typography.bodyStrong,fontSize:11,letterSpacing:2},title:{color:colors.text,fontFamily:typography.display,fontSize:32},description:{color:colors.textSecondary,fontFamily:typography.body,lineHeight:21,maxWidth:760},grid:{flexDirection:'row',flexWrap:'wrap',gap:16},card:{width:'100%',maxWidth:520,flexGrow:1,padding:18,gap:10},row:{flexDirection:'row',alignItems:'center',gap:9},sectionTitle:{color:colors.text,fontFamily:typography.display,fontSize:22},cardTitle:{color:colors.text,fontFamily:typography.bodyStrong,fontSize:15,flex:1},status:{color:colors.brand,fontFamily:typography.bodyStrong,fontSize:11},meta:{color:colors.textSecondary,fontFamily:typography.body,fontSize:13,lineHeight:19},tabs:{flexDirection:'row',flexWrap:'wrap',gap:8},loader:{margin:50}});
