import React, { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Check, ShieldOff, X } from 'lucide-react-native';
import { useGovernanceAuth } from '../../contexts/governance-auth-context';
import { AppButton } from '../ui/AppButton';
import { AppCard } from '../ui/AppCard';
import { AppInput } from '../ui/AppInput';
import { InlineNotice } from '../ui/InlineNotice';
import { colors, layout, typography } from '../../theme/tokens';
import { executePrivacyRequest, listPrivacyRequests, rejectPrivacyRequest, submitPrivacyRequest } from '../../services/governance-compliance';
import type { PrivacyRequest } from '../../types/governance-compliance';

export function GovernancePrivacy() {
  const { profile } = useGovernanceAuth(); const canWrite = profile?.role === 'SaaS_Editor' || profile?.role === 'SaaS_Owner';
  const [items,setItems]=useState<PrivacyRequest[]>([]); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState<{tone:'success'|'danger';message:string}|null>(null); const [active,setActive]=useState<string|null>(null); const [reason,setReason]=useState(''); const [targetProfileId,setTargetProfileId]=useState('');
  const load=async()=>{setLoading(true);try{setItems(await listPrivacyRequests());}catch(e){setNotice({tone:'danger',message:e instanceof Error?e.message:'Não foi possível carregar a fila LGPD.'});}finally{setLoading(false);}}; useEffect(()=>{void load();},[]);
  const run=async(id:string,kind:'execute'|'reject')=>{if(reason.trim().length<10){setNotice({tone:'danger',message:'A confirmação exige uma justificativa de pelo menos 10 caracteres.'});return;}setActive(id);try{if(kind==='execute')await executePrivacyRequest(id,reason);else await rejectPrivacyRequest(id,reason);setNotice({tone:'success',message:kind==='execute'?'Exclusão auditada executada de forma idempotente.':'Solicitação LGPD rejeitada.'});setReason('');await load();}catch(e){setNotice({tone:'danger',message:e instanceof Error?e.message:'A ação não foi concluída.'});}finally{setActive(null);}};
  const submit = async () => { if (!targetProfileId.trim() || reason.trim().length < 10) { setNotice({ tone: 'danger', message: 'Informe um profile_id existente e uma justificativa de pelo menos 10 caracteres.' }); return; } setActive('submit'); try { await submitPrivacyRequest(targetProfileId.trim(), reason); setNotice({ tone: 'success', message: 'Solicitação LGPD criada.' }); setTargetProfileId(''); setReason(''); await load(); } catch (e) { setNotice({ tone: 'danger', message: e instanceof Error ? e.message : 'Não foi possível criar a solicitação.' }); } finally { setActive(null); } };
  return <ScrollView contentContainerStyle={styles.page} testID="governance-privacy-screen"><Text style={styles.eyebrow}>DIREITOS DO TITULAR</Text><Text style={styles.title}>Privacidade e exclusão auditada</Text><Text style={styles.description}>A execução anonimiza o perfil, revoga os vínculos e remove a identidade de autenticação antes de concluir a solicitação. Falhas parciais permanecem recuperáveis.</Text>{!!notice&&<InlineNotice tone={notice.tone} message={notice.message}/>}<AppCard style={styles.card}><Text style={styles.sectionTitle}>Nova solicitação</Text><AppInput label="profile_id já cadastrado" value={targetProfileId} onChangeText={setTargetProfileId} placeholder="UUID do perfil"/><AppInput label="Justificativa" value={reason} onChangeText={setReason} placeholder="Explique o impacto e a base da decisão" multiline/><AppButton label="Enviar para a fila" onPress={()=>void submit()} loading={active==='submit'}/></AppCard>{loading?<ActivityIndicator color={colors.brand} style={styles.loader}/>:items.length===0?<AppCard style={styles.empty}><ShieldOff color={colors.success} size={22}/><Text style={styles.emptyTitle}>Fila vazia</Text><Text style={styles.meta}>Nenhuma solicitação de exclusão encontrada.</Text></AppCard>:<View style={styles.grid}>{items.map(item=><AppCard key={item.id} style={styles.card} testID={`privacy-request-${item.id}`}><View style={styles.row}><Text style={styles.cardTitle}>{item.target_name}</Text><Text style={styles.status}>{item.status}</Text></View><Text style={styles.meta}>Solicitada em {new Date(item.created_at).toLocaleDateString('pt-BR')}</Text><Text style={styles.meta}>{item.request_reason}</Text>{canWrite&&(item.status==='pending'||item.status==='failed')&&<View style={styles.actions}><AppButton label={item.status==='failed'?'Tentar novamente':'Executar exclusão'} onPress={()=>void run(item.id,'execute')} loading={active===item.id} icon={<Check size={15} color={colors.ink}/>}/>{item.status==='pending'&&<AppButton label="Rejeitar" onPress={()=>void run(item.id,'reject')} loading={active===item.id} variant="danger" icon={<X size={15} color={colors.danger}/>}/>}</View>}</AppCard>)}</View>}</ScrollView>;
}
const styles=StyleSheet.create({page:{width:'100%',maxWidth:layout.contentMax,alignSelf:'center',padding:24,gap:16,paddingBottom:80},eyebrow:{color:colors.brand,fontFamily:typography.bodyStrong,fontSize:11,letterSpacing:2},title:{color:colors.text,fontFamily:typography.display,fontSize:32},description:{color:colors.textSecondary,fontFamily:typography.body,lineHeight:21,maxWidth:760},grid:{flexDirection:'row',flexWrap:'wrap',gap:16},card:{width:'100%',maxWidth:480,flexGrow:1,padding:18,gap:8},row:{flexDirection:'row',justifyContent:'space-between',gap:10},sectionTitle:{color:colors.text,fontFamily:typography.display,fontSize:21},cardTitle:{color:colors.text,fontFamily:typography.display,fontSize:20,flex:1},status:{color:colors.brand,fontFamily:typography.bodyStrong,fontSize:11,textTransform:'uppercase'},meta:{color:colors.textSecondary,fontFamily:typography.body,fontSize:13,lineHeight:19},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},loader:{margin:50},empty:{padding:26,gap:10},emptyTitle:{color:colors.text,fontFamily:typography.display,fontSize:22}});
