import React, { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Check, Search, X } from 'lucide-react-native';
import { useGovernanceAuth } from '../../contexts/governance-auth-context';
import { AppButton } from '../ui/AppButton';
import { AppCard } from '../ui/AppCard';
import { AppInput } from '../ui/AppInput';
import { InlineNotice } from '../ui/InlineNotice';
import { colors, layout, radii, typography } from '../../theme/tokens';
import { useRouter } from 'expo-router';
import { approveGovernanceRequest, listGovernanceRequests, rejectGovernanceRequest } from '../../services/governance-compliance';
import type { GovernanceRequest } from '../../types/governance-compliance';

export function GovernanceRequests() {
  const { profile } = useGovernanceAuth();
  const router = useRouter();
  const canWrite = profile?.role === 'SaaS_Editor' || profile?.role === 'SaaS_Owner';
  const [items, setItems] = useState<GovernanceRequest[]>([]);
  const [search, setSearch] = useState(''); const [status, setStatus] = useState<string | null>('pending');
  const [reasonId, setReasonId] = useState<string | null>(null); const [reason, setReason] = useState('');
  const [action, setAction] = useState<{ id: string; kind: 'approve' | 'reject' } | null>(null);
  const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<{ tone: 'success'|'danger'; message: string } | null>(null);
  const load = async () => { setLoading(true); try { setItems(await listGovernanceRequests({ searchTerm: search, status })); } catch (e) { setNotice({ tone: 'danger', message: e instanceof Error ? e.message : 'Não foi possível carregar a fila.' }); } finally { setLoading(false); } };
  useEffect(() => { const t = setTimeout(() => { void load(); }, 0); return () => clearTimeout(t); }, [status]);
  const run = async (item: GovernanceRequest, kind: 'approve'|'reject') => { if (reason.trim().length < 10) { setNotice({ tone: 'danger', message: 'Informe uma justificativa com pelo menos 10 caracteres.' }); return; } setAction({ id: item.id, kind }); try { if (kind === 'approve') await approveGovernanceRequest(item.id, reason); else await rejectGovernanceRequest(item.id, reason); setNotice({ tone: 'success', message: kind === 'approve' ? 'Solicitação aprovada e convite administrativo gerado.' : 'Solicitação rejeitada.' }); setReasonId(null); setReason(''); await load(); } catch (e) { setNotice({ tone: 'danger', message: e instanceof Error ? e.message : 'A ação não foi concluída.' }); } finally { setAction(null); } };
  return <ScrollView contentContainerStyle={styles.page} testID="governance-requests-screen"><Text style={styles.eyebrow}>CONFORMIDADE</Text><Text style={styles.title}>Solicitações de estabelecimento</Text><Text style={styles.description}>Revise a origem, os dados cadastrais e a justificativa antes de liberar o convite administrativo.</Text>
    <View style={styles.filters}><AppInput label="Buscar" testID="governance-requests-search" value={search} onChangeText={setSearch} placeholder="Nome, slug, solicitante ou documento" icon={<Search size={16} color={colors.textMuted} />} /><View style={styles.tabs}>{['pending','approved','rejected'].map((value) => <AppButton key={value} label={value === 'pending' ? 'Pendentes' : value === 'approved' ? 'Aprovadas' : 'Rejeitadas'} onPress={() => setStatus(value)} variant={status === value ? 'primary' : 'secondary'} size="sm" />)}</View><AppButton label="Atualizar" onPress={() => void load()} variant="secondary" size="sm" /></View>
    {!!notice && <InlineNotice tone={notice.tone} message={notice.message} />}
    {loading ? <ActivityIndicator color={colors.brand} style={styles.loader} /> : items.length === 0 ? <AppCard style={styles.empty}><Text style={styles.emptyTitle}>Nenhuma solicitação nesta fila</Text><Text style={styles.meta}>A busca e o filtro atuais não retornaram registros.</Text></AppCard> : <View style={styles.grid}>{items.map((item) => <AppCard key={item.id} style={styles.card} testID={`governance-request-${item.id}`}><View style={styles.row}><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.status}>{item.status}</Text></View><Text style={styles.slug}>cutsync.com/{item.slug}</Text><Text style={styles.meta}>{item.requester_name} · {item.requester_email}</Text>{item.document_number && <Text style={styles.meta}>Documento: {item.document_number}</Text>}{item.address && <Text style={styles.meta}>{item.address}</Text>}<AppButton label="Ver detalhe" variant="secondary" size="sm" onPress={() => router.push(`/governance/requests/${item.id}`)} />{canWrite && item.status === 'pending' && (reasonId === item.id ? <View style={styles.reason}><AppInput label="Justificativa obrigatória" testID={`governance-request-${item.id}-reason`} value={reason} onChangeText={setReason} multiline placeholder="Explique a decisão" /><View style={styles.actions}><AppButton label="Confirmar aprovação" onPress={() => void run(item, 'approve')} loading={action?.id === item.id && action.kind === 'approve'} icon={<Check size={15} color={colors.ink} />} /><AppButton label="Confirmar rejeição" onPress={() => void run(item, 'reject')} loading={action?.id === item.id && action.kind === 'reject'} variant="danger" icon={<X size={15} color={colors.danger} />} /><AppButton label="Cancelar" onPress={() => { setReasonId(null); setReason(''); }} variant="secondary" /></View></View> : <View style={styles.actions}><AppButton label="Aprovar" onPress={() => { setReasonId(item.id); setReason(''); }} icon={<Check size={15} color={colors.ink} />} /><AppButton label="Rejeitar" onPress={() => { setReasonId(item.id); setReason(''); }} variant="danger" icon={<X size={15} color={colors.danger} />} /></View>)}</AppCard>)}</View>}
  </ScrollView>;
}
const styles = StyleSheet.create({ page: { width: '100%', maxWidth: layout.contentMax, alignSelf: 'center', padding: 24, gap: 16, paddingBottom: 80 }, eyebrow: { color: colors.brand, fontFamily: typography.bodyStrong, fontSize: 11, letterSpacing: 2 }, title: { color: colors.text, fontFamily: typography.display, fontSize: 32 }, description: { color: colors.textSecondary, fontFamily: typography.body, lineHeight: 21, maxWidth: 760 }, filters: { gap: 12 }, tabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 }, card: { width: '100%', maxWidth: 430, flexGrow: 1, padding: 18 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 }, cardTitle: { color: colors.text, fontFamily: typography.display, fontSize: 21, flex: 1 }, status: { color: colors.brand, fontFamily: typography.bodyStrong, fontSize: 11, textTransform: 'uppercase' }, slug: { color: colors.brand, fontFamily: typography.bodyStrong, fontSize: 12, marginTop: 5 }, meta: { color: colors.textSecondary, fontFamily: typography.body, fontSize: 13, lineHeight: 19, marginTop: 8 }, reason: { marginTop: 14, gap: 10 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, loader: { margin: 50 }, empty: { padding: 24 }, emptyTitle: { color: colors.text, fontFamily: typography.display, fontSize: 21 },
});
