import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Check, FileCheck2, Upload, X } from 'lucide-react-native';
import { useGovernanceAuth } from '../../contexts/governance-auth-context';
import { AppButton } from '../ui/AppButton';
import { AppCard } from '../ui/AppCard';
import { AppInput } from '../ui/AppInput';
import { InlineNotice } from '../ui/InlineNotice';
import { colors, layout, radii, typography } from '../../theme/tokens';
import { listGovernanceEstablishments } from '../../services/governance-operations';
import { getSignedKycDocument, listVerificationReviews, reviewVerification, submitVerification, uploadKycDocument } from '../../services/governance-compliance';
import type { GovernanceEstablishmentListItem } from '../../types/governance-knowledge';
import type { VerificationReview } from '../../types/governance-compliance';

export function GovernanceVerification() {
  const { profile } = useGovernanceAuth(); const canWrite = profile?.role === 'SaaS_Editor' || profile?.role === 'SaaS_Owner';
  const [establishments, setEstablishments] = useState<GovernanceEstablishmentListItem[]>([]); const [reviews, setReviews] = useState<VerificationReview[]>([]); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<{tone:'success'|'danger';message:string}|null>(null); const [reason, setReason] = useState(''); const [activeId, setActiveId] = useState<string|null>(null); const [reviewReason, setReviewReason] = useState(''); const [reviewId, setReviewId] = useState<string|null>(null);
  const load = async () => { setLoading(true); try { const [e, r] = await Promise.all([listGovernanceEstablishments({ pageSize: 100 }), listVerificationReviews()]); setEstablishments(e); setReviews(r); } catch (e) { setNotice({tone:'danger',message:e instanceof Error?e.message:'Não foi possível carregar a verificação.'}); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const chooseFile = (establishmentId: string) => { if (typeof document === 'undefined') return; const input = document.createElement('input'); input.type='file'; input.accept='application/pdf,image/jpeg,image/png'; input.onchange = async () => { const file = input.files?.[0]; if (!file) return; if (file.size > 10*1024*1024) { setNotice({tone:'danger',message:'O documento deve ter no máximo 10 MB.'}); return; } if (!reason.trim() || reason.trim().length < 10) { setNotice({tone:'danger',message:'Informe a justificativa do envio antes de selecionar o arquivo.'}); return; } setActiveId(establishmentId); try { const uploaded = await uploadKycDocument(file, file.type, establishmentId); await submitVerification(establishmentId, uploaded.path, reason); setNotice({tone:'success',message:'Documento enviado para revisão.'}); setReason(''); await load(); } catch (e) { setNotice({tone:'danger',message:e instanceof Error?e.message:'Falha no upload.'}); } finally { setActiveId(null); } }; input.click(); };
  const decide = async (id: string, decision: 'approved'|'rejected') => { if (reviewReason.trim().length < 10) { setNotice({tone:'danger',message:'A decisão exige uma justificativa de pelo menos 10 caracteres.'}); return; } setReviewId(id); try { await reviewVerification(id, decision, reviewReason); setNotice({tone:'success',message: decision==='approved'?'KYC aprovado.':'KYC rejeitado.'}); setReviewReason(''); await load(); } catch(e) { setNotice({tone:'danger',message:e instanceof Error?e.message:'Falha na revisão.'}); } finally { setReviewId(null); } };
  return <ScrollView contentContainerStyle={styles.page} testID="governance-verification-screen"><Text style={styles.eyebrow}>CONFORMIDADE</Text><Text style={styles.title}>Verificação cadastral</Text><Text style={styles.description}>Documentos ficam em bucket privado e cada decisão gera uma revisão rastreável.</Text>{!!notice&&<InlineNotice tone={notice.tone} message={notice.message}/>}<AppInput label="Justificativa do envio" value={reason} onChangeText={setReason} placeholder="Por que este documento está sendo enviado?" multiline hint="PDF, JPEG ou PNG, até 10 MB."/>{loading?<ActivityIndicator color={colors.brand} style={styles.loader}/>:<View style={styles.grid}>{establishments.filter((e)=>e.kyc_status!=='approved').map((e)=><AppCard key={e.id} style={styles.card}><View style={styles.row}><FileCheck2 color={colors.brand} size={20}/><Text style={styles.cardTitle}>{e.name}</Text><Text style={styles.status}>{e.kyc_status||'unsubmitted'}</Text></View><Text style={styles.meta}>Nível atual: {e.verification_level||1}</Text>{canWrite&&<AppButton label="Enviar documento privado" onPress={()=>chooseFile(e.id)} loading={activeId===e.id} icon={<Upload size={15} color={colors.ink}/>}/>}</AppCard>)}</View>}{reviews.length>0&&<View style={styles.reviewSection}><Text style={styles.sectionTitle}>Revisões recentes</Text>{reviews.map((r)=><AppCard key={r.id} style={styles.card}><View style={styles.row}><Text style={styles.cardTitle}>{r.establishment_name}</Text><Text style={styles.status}>{r.decision}</Text></View><Text style={styles.meta}>{r.reason}</Text>{r.document_path&&<Pressable accessibilityRole="link" onPress={async()=>{try{const signed=await getSignedKycDocument(r.document_path!); if(typeof window!=='undefined') window.open(signed.signedUrl,'_blank');}catch(e){setNotice({tone:'danger',message:e instanceof Error?e.message:'Falha ao gerar URL.'});}}}><Text style={styles.link}>Visualizar documento (URL assinada)</Text></Pressable>}{canWrite&&r.decision==='submitted'&&<><AppInput label="Justificativa da decisão" value={reviewReason} onChangeText={setReviewReason} placeholder="Explique a decisão" multiline/><View style={styles.actions}><AppButton label="Aprovar KYC" onPress={()=>void decide(r.id,'approved')} loading={reviewId===r.id} icon={<Check size={15} color={colors.ink}/>}/><AppButton label="Rejeitar KYC" onPress={()=>void decide(r.id,'rejected')} loading={reviewId===r.id} variant="danger" icon={<X size={15} color={colors.danger}/>}/></View></>}</AppCard>)}</View>}</ScrollView>;
}
const styles=StyleSheet.create({page:{width:'100%',maxWidth:layout.contentMax,alignSelf:'center',padding:24,gap:16,paddingBottom:80},eyebrow:{color:colors.brand,fontFamily:typography.bodyStrong,fontSize:11,letterSpacing:2},title:{color:colors.text,fontFamily:typography.display,fontSize:32},description:{color:colors.textSecondary,fontFamily:typography.body,lineHeight:21,maxWidth:760},grid:{flexDirection:'row',flexWrap:'wrap',gap:16},card:{width:'100%',maxWidth:520,flexGrow:1,padding:18,gap:8},row:{flexDirection:'row',alignItems:'center',gap:9},cardTitle:{color:colors.text,fontFamily:typography.display,fontSize:20,flex:1},status:{color:colors.brand,fontFamily:typography.bodyStrong,fontSize:11,textTransform:'uppercase'},meta:{color:colors.textSecondary,fontFamily:typography.body,fontSize:13,lineHeight:19},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},reviewSection:{gap:12},sectionTitle:{color:colors.text,fontFamily:typography.display,fontSize:23},link:{color:colors.brand,fontFamily:typography.bodyStrong,fontSize:13},loader:{margin:50}});
