import { StyleSheet } from 'react-native';

import { colors, layout, spacing, typeScale } from '@/theme/tokens';

export const billingStyles = StyleSheet.create({
  scrollContent: { flexGrow: 1 },
  navigation: {
    minWidth: '100%',
    gap: spacing.xs,
    padding: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  navigationItem: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    borderRadius: 8,
  },
  navigationItemSelected: { backgroundColor: colors.brandSoft },
  navigationLabel: { ...typeScale.smallStrong, color: colors.textSecondary },
  navigationLabelSelected: { color: colors.brandPrimary },
  loading: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  periodRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  periodMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing.sm,
  },
  overviewLinks: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  overviewLink: {
    width: 260,
    maxWidth: '100%',
    gap: spacing.xs,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  overviewLinkTitle: { ...typeScale.bodyStrong, color: colors.text },
  overviewLinkDetail: { ...typeScale.small, color: colors.textSecondary },
  formCard: { maxWidth: layout.formMax },
  cardHeading: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  cardTitle: { ...typeScale.cardTitle, color: colors.text },
  bodyText: { ...typeScale.body, color: colors.textSecondary },
  planOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  planOption: {
    minWidth: 180,
    flex: 1,
    gap: spacing.xs,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
  },
  planOptionSelected: {
    borderColor: colors.brandPrimary,
    backgroundColor: colors.brandSoft,
  },
  planOptionLabel: { ...typeScale.bodyStrong, color: colors.text },
  planOptionLabelSelected: { color: colors.brandPrimary },
  planOptionCode: { ...typeScale.small, color: colors.textMuted },
  disabled: { opacity: 0.55 },
  sectionStack: { width: '100%', gap: spacing.md },
  accountHeading: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  accountIdentity: { flex: 1, minWidth: 220, gap: spacing.xs },
  accountFacts: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xl },
  fact: { minWidth: 160, gap: spacing.xs },
  factLabel: { ...typeScale.label, color: colors.textMuted, textTransform: 'uppercase' },
  factValue: { ...typeScale.bodyStrong, color: colors.text },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  stripCard: { paddingVertical: spacing.sm },
  strip: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  stripCell: {
    flexGrow: 1,
    flexBasis: 160,
    minWidth: 140,
    gap: 6,
    padding: spacing.sm,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: colors.border,
  },
  stripLabel: { ...typeScale.label, color: colors.textMuted, textTransform: 'uppercase' },
  stripValue: {
    ...typeScale.metric,
    fontSize: 22,
    lineHeight: 28,
    color: colors.text,
    fontVariant: ['tabular-nums'],
  },
  stripDetail: { ...typeScale.small, color: colors.textSecondary },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  panel: { flexGrow: 1, flexBasis: 320, gap: spacing.sm },
  panelWide: { flexBasis: 480 },
  panelHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
  },
  opList: { gap: spacing.xs },
  opRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  opMain: { flex: 1, gap: 2 },
  opLabel: { ...typeScale.smallStrong, color: colors.text },
  opDetail: { ...typeScale.small, color: colors.textSecondary },
  opCount: {
    ...typeScale.bodyStrong,
    color: colors.text,
    fontVariant: ['tabular-nums'],
  },
  opChevron: { ...typeScale.bodyStrong, color: colors.textMuted },
  textLink: { ...typeScale.smallStrong, color: colors.accent },
  textLinkWrap: { alignSelf: 'flex-start', marginTop: spacing.xs },
  metaText: { ...typeScale.small, color: colors.textMuted },
  metaStrong: { ...typeScale.smallStrong, color: colors.text },
  toolbarCard: { gap: spacing.sm },
  toolbar: { gap: spacing.sm },
  searchField: { maxWidth: 360 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, alignItems: 'center' },
  filterChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.surfaceMuted,
  },
  filterChipOn: {
    borderColor: colors.brandPrimary,
    backgroundColor: colors.brandSoft,
  },
  filterChipText: { ...typeScale.small, color: colors.text },
  split: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md },
  splitCompact: { flexDirection: 'column' },
  tablePane: { flex: 1, minWidth: 0, gap: spacing.sm },
  table: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  tableHead: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceMuted,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 56,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  tableRowSelected: { backgroundColor: colors.brandSoft },
  headCell: { ...typeScale.label, color: colors.textMuted, textTransform: 'uppercase' },
  cell: { ...typeScale.small, color: colors.text },
  cellStrong: { ...typeScale.smallStrong, color: colors.text },
  cellMono: {
    ...typeScale.small,
    color: colors.textMuted,
    fontFamily: 'monospace',
  },
  colOrg: { flex: 1.4, minWidth: 140 },
  colPlan: { flex: 1, minWidth: 90 },
  colState: { flex: 0.9, minWidth: 90 },
  colBlock: { flex: 0.7, minWidth: 70 },
  colUnits: { flex: 0.8, minWidth: 80 },
  colPeriod: { flex: 0.9, minWidth: 90 },
  mobileCard: {
    gap: spacing.xs,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
  },
  drawer: {
    width: 360,
    maxWidth: '100%',
    gap: spacing.sm,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
  },
  drawerFull: { width: '100%' },
  drawerHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  drawerName: { ...typeScale.sectionTitle, color: colors.text },
  defList: { gap: spacing.xs },
  defRow: {
    gap: 2,
    paddingVertical: spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  defLabel: { ...typeScale.label, color: colors.textMuted, textTransform: 'uppercase' },
  defValue: { ...typeScale.body, color: colors.text },
  actionList: { gap: spacing.xs },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surfaceMuted,
  },
  inlineSelect: { gap: spacing.xs },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 20, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  modalCard: {
    width: '100%',
    maxWidth: 480,
    gap: spacing.md,
  },
});
