import { StyleSheet } from 'react-native';

import { colors, layout, spacing, typeScale } from '@/theme/tokens';

export const billingStyles = StyleSheet.create({
  scrollContent: { flexGrow: 1 },
  navigation: {
    minWidth: '100%',
    gap: spacing.xs,
    padding: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  navigationItem: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    borderRadius: 8,
  },
  navigationItemSelected: { backgroundColor: colors.brandSoft },
  navigationLabel: { ...typeScale.smallStrong, color: colors.textSecondary },
  navigationLabelSelected: { color: colors.brandPrimary },
  loading: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  overviewLinks: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  overviewLink: {
    width: 260,
    maxWidth: '100%',
    gap: spacing.xs,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  overviewLinkTitle: { ...typeScale.bodyStrong, color: colors.text },
  overviewLinkDetail: { ...typeScale.small, color: colors.textSecondary },
  formCard: { maxWidth: layout.formMax },
  cardHeading: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  cardTitle: { ...typeScale.cardTitle, color: colors.text },
  bodyText: { ...typeScale.body, color: colors.textSecondary },
  planOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  planOption: {
    minWidth: 180,
    flex: 1,
    gap: spacing.xs,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
  },
  planOptionSelected: {
    borderColor: colors.brandPrimary,
    backgroundColor: colors.brandSoft,
  },
  planOptionLabel: { ...typeScale.bodyStrong, color: colors.text },
  planOptionLabelSelected: { color: colors.brandPrimary },
  planOptionCode: { ...typeScale.small, color: colors.textMuted },
  disabled: { opacity: 0.55 },
  sectionStack: { width: '100%', gap: spacing.md },
  accountHeading: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  accountIdentity: { flex: 1, minWidth: 220, gap: spacing.xs },
  accountFacts: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xl },
  fact: { minWidth: 160, gap: spacing.xs },
  factLabel: { ...typeScale.label, color: colors.textMuted, textTransform: 'uppercase' },
  factValue: { ...typeScale.bodyStrong, color: colors.text },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
});
