import { expect, test } from '@playwright/test';

import { normalizeTotpQrCode } from '../../packages/domain/src/totp-qr-code';

const svg = '<?xml version="1.0"?>\n'
  + '<!-- Generated by SVGo -->\n'
  + '<svg xmlns="http://www.w3.org/2000/svg">\n'
  + '<path fill="#000" d="M0 0h10v10H0z"/>\n'
  + '</svg>';
const reactNativeWebSvgDataUriPattern = /^(data:image\/svg\+xml;utf8,)(.*)/;

test('normalizes the Supabase XML-prefixed SVG for React Native Web', () => {
  const result = normalizeTotpQrCode(`data:image/svg+xml;utf-8,${svg}`);
  const match = result.match(reactNativeWebSvgDataUriPattern);

  expect(match).not.toBeNull();
  expect(result).toBe(
    'data:image/svg+xml;utf8,'
    + '<svg xmlns="http://www.w3.org/2000/svg"> '
    + '<path fill="#000" d="M0 0h10v10H0z"/> '
    + '</svg>',
  );

  const resolvedSource = `${match?.[1]}${encodeURIComponent(match?.[2] ?? '')}`;
  expect(resolvedSource).toContain('%23000');
  expect(resolvedSource).not.toContain('fill="#000"');
});

test('decodes and normalizes an already percent-encoded SVG data URL', () => {
  const result = normalizeTotpQrCode(
    `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`,
  );

  expect(result).toBe(
    'data:image/svg+xml;utf8,'
    + '<svg xmlns="http://www.w3.org/2000/svg"> '
    + '<path fill="#000" d="M0 0h10v10H0z"/> '
    + '</svg>',
  );
});

test('preserves base64 and non-SVG sources', () => {
  expect(normalizeTotpQrCode('data:image/svg+xml;base64,PHN2Zy8+')).toBe(
    'data:image/svg+xml;base64,PHN2Zy8+',
  );
  expect(normalizeTotpQrCode('https://example.test/qr.svg')).toBe(
    'https://example.test/qr.svg',
  );
});
